[AWIBOF-6320] Add RAID6 option to CLI array commands
poseidonos/poseidonos pull request #114
Opened 2022-06-10 09:32 UTC by junghyun-34

Add RAID6 options and examples to CLI array commands.

Add RAID6 options and examples to CREATEARRAY and AUTOCREATEARRAY commands for futher support.

Signed-off-by: Junghyun Hong <jh34.hong@samsung.com>

2022-06-11 04:40 UTC, mjlee34 commented on tool/cli/cmd/arraycmds/create_array.go
> +	-d nvme-device0,nvme-device1,nvme-device2,nvme-device3 -s nvme-device4 -r RAID6
가독성을 위해 33-34 라인 사이에 공백이 필요할 것 같습니다. :)

2022-06-13 00:47 UTC, mjlee34 commented on doc/guides/cli/poseidonos-cli_array_autocreate.md
> +	poseidonos-cli array autocreate -a Array1 -b uram0 -d 4 -s 1 -r RAID6
정현님, 가독성을 위해 Example 1: 과 Example 2:로 나누는게 좋을 것 같습니다. 공백도 한줄 필요할 것 같습니다. list_array.go 파일 참조 부탁드립니다.

2022-06-13 00:47 UTC, mjlee34 commented on tool/cli/cmd/arraycmds/create_array.go
> +	poseidonos-cli array create -a Array0 -buffer device0
여기도 Example 1, Example 2로 나눠야 할 것 같습니다.

2022-06-13 02:32 UTC, junghyun-34 commented on doc/guides/cli/poseidonos-cli_array_autocreate.md
> +	poseidonos-cli array autocreate -a Array1 -b uram0 -d 4 -s 1 -r RAID6
좋은 의견 감사드립니다. 수정하겠습니다 :-)

2022-06-13 03:05 UTC, hsung-yang commented on tool/cli/cmd/arraycmds/autocreate_array.go
> +Example 1 (without specifying RAID - default RAID level is used):
default raid level이 무엇인지 알려주는 것도 좋을 것 같습니다

2022-06-13 03:07 UTC, hsung-yang commented on tool/cli/cmd/arraycmds/autocreate_array.go
> +	poseidonos-cli array autocreate --array-name Array0 --buffer uram0 --num-data-devs 3 --num-spaer 1 --raid RAID6
spaer 오타가 있습니다

2022-06-13 03:09 UTC, hsung-yang requested changes
커맨트로 남긴 typo만 수정해주시면 될 것 같습니다~

2022-06-13 03:13 UTC, mjlee34 commented on tool/cli/cmd/arraycmds/autocreate_array.go
> +Example 1 (without specifying RAID - default RAID level is used):
이게 여기 String으로 쓰게 되면, 아마 향후 변경시 놓칠 수 있을 것 같습니다. 
Default Level은 Help Message 출력시 Flag 설명에 나오게 되어 있습니다.

2022-06-13 03:17 UTC, mjlee34 approved these changes
LGTM

2022-06-13 03:20 UTC, hsung-yang approved these changes
LGTM

2022-06-13 04:16 UTC, merged