[AWIBOF-5118] Add RAID6 to POS array fault-tolerance
poseidonos/poseidonos pull request #115
Opened 2022-06-10 11:19 UTC by junghyun-34

Add RAID6 to POS array fault-tolerance.

Add draft version of RAID6 and options for stripe partition and raid types for future support.

Signed-off-by: Junghyun Hong <jh34.hong@samsung.com>

2022-06-15 03:52 UTC, mjlee34 commented on src/array/ft/raid6.cpp
> +   if(lastIndex<pParityIndex && pParityIndex<qParityIndex){
POS 코드 컨벤션은 중괄호를 새 줄에 놓습니다.
이동 부탁드립니다 :smiley:

2022-06-15 03:53 UTC, mjlee34 commented on src/array/partition/stripe_partition.cpp
> +   {
인덴트 확인 부탁드립니다. GitHub에서 좀 깨지는 걸지도 모르겠네요 :thinking:

2022-06-15 03:55 UTC, mjlee34 commented on src/array/ft/raid6.cpp
> +   BlkOffset startOffset = le.addr.offset;
워낙에 Low-level 복잡한 연산이다 보니, 주석으로 RAID6 계산의 어떤 단계인지 (어떤 Matrix를 계산하는건지, 어떤 의미인지) 적어주시면 가독성이 크게 향상될 것 같습니다. 😄

2022-06-15 03:57 UTC, mjlee34 commented on src/array/ft/raid6.cpp
> +       POS_TRACE_DEBUG(EID(RAID_DEBUG_MSG), "BufferPool for RAID6 is created, {}", pool->GetOwner());
향후에 RAID6 코드에서도 Log를 강화해주시면 감사하겠습니다. 🙏

2022-06-15 03:59 UTC, mjlee34 commented on src/array/ft/raid6.h
> +   virtual list<FtEntry> Translate(const LogicalEntry& le) override;
RAID6 Encoding/Decoding의 Unit Testing을 추가할 수는 없을까요? 워낙 어려운 작업 해주셨는데, main에 머지되고 나서 문제가 생길까봐 우려가 됩니다. Unit Testing도 같이 추가하면 향후 유지보수 시 좋을 것 같습니다.  👍

2022-06-15 04:00 UTC, mjlee34 commented on src/array/ft/raid6.cpp
> +        for(i=0;i<parityBufferCnt;i++){
for 문 내 띄어쓰기가 필요할 것 같습니다. 다른 코드 참고하셔서 컨벤션 확인 부탁드립니다. 😃

2022-06-15 04:02 UTC, mjlee34 reviewed
고생 많이 하셨습니다. 커멘트 확인 부탁드립니다. 👍

2022-06-15 04:37 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +       POS_TRACE_DEBUG(EID(RAID_DEBUG_MSG), "BufferPool for RAID6 is created, {}", pool->GetOwner());
POS_TRACE_DEBUG이군요! 코드 개선에 적극 반영하겠습니다.

2022-06-15 04:38 UTC, junghyun-34 commented on src/array/ft/raid6.h
> +   virtual list<FtEntry> Translate(const LogicalEntry& le) override;
네 UT도 공부해서 추가하고 동작 확인되면 merge하는것을 목표로 하겠습니다!

2022-06-15 04:39 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +        for(i=0;i<parityBufferCnt;i++){
넵! 다음 커밋에 반영하겠습니다. 감사합니다.

2022-06-15 04:39 UTC, junghyun-34 commented on src/array/partition/stripe_partition.cpp
> +   {
넵! 다음 커밋에 반영하겠습니다. 감사합니다.

2022-06-15 04:39 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +   if(lastIndex<pParityIndex && pParityIndex<qParityIndex){
넵! 다음 커밋에 반영하겠습니다. 감사합니다.

2022-06-15 04:40 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +   BlkOffset startOffset = le.addr.offset;
넵! 다음 커밋에 반영하겠습니다. 감사합니다.

2022-06-15 04:58 UTC, hsung-yang commented on src/array/ft/raid6.cpp
> +        for(i=0;i<parityBufferCnt;i++){
위키에 formatter 돌리는 방법이 있을텐데 그 문서 참조하시면 쉽게 하실 수 있을 것 같습니다

2022-06-15 05:00 UTC, hsung-yang commented on src/array/ft/raid6.cpp
> +        for(i=0;i<parityBufferCnt;i++){
http://globalwiki.itplatform.sec.samsung.net:8099/pages/viewpage.action?pageId=39928726

2022-06-15 05:07 UTC, minjoon-ahn requested changes

2022-06-15 05:07 UTC, minjoon-ahn commented on src/array/ft/raid6.cpp
> +   srcBufferCnt= raid6BufferCnt-parityBufferCnt;
srcBufferCnt가 의미하는것이 무엇인가요?

2022-06-15 05:07 UTC, minjoon-ahn commented on src/array/ft/raid6.cpp
> +   raid6BufferSize = ArrayConfig::BLOCK_SIZE_BYTE;
raid6BufferSize라는 멤버변수로 별도 할당이 필요한가요?

2022-06-15 05:07 UTC, minjoon-ahn commented on src/array/ft/raid6.cpp
> +{
구현이 안된부분 같은데 주석을 추가해주세요

2022-06-15 07:36 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +   raid6BufferCnt=ftSize_.blksPerChunk;
네 일괄 반영하겠습니다!

2022-06-15 07:37 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +   raid6BufferSize = ArrayConfig::BLOCK_SIZE_BYTE;
ec_encode_data API의 첫번째 인자로 버퍼의 길이를 전달해 주어야 합니다. 변수명을 Length관련으로 수정할까요?

2022-06-15 07:40 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +   srcBufferCnt= raid6BufferCnt-parityBufferCnt;
전체 Device의 수 - Parity Device의 수여서 Chunk당 Block수-2입니다. RS Code의 상수 Table생성할때 API에서 입력을 받는데별도 변수로 설정 안하고 raid6BufferCnt-parityBufferCnt로 넣어주어도 됩니다. 의견 주시면 반영하겠습니다.

2022-06-15 07:42 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +       .backupBlkCnt = pSize->blksPerChunk,
2배가 되는게 맞습니다. 수정하겠습니다.

2022-06-15 07:54 UTC, junghyun-34 commented on src/array/ft/raid6.cpp
> +        for(i=0;i<parityBufferCnt;i++){
@hsung-yang clang-format으로 일괄 수정할수 있었습니다. 감사합니다!!

2022-06-21 03:21 UTC, hsung-yang approved these changes
LGTM

2022-06-21 06:01 UTC, Seochokid requested changes

2022-06-21 06:01 UTC, Seochokid commented on package/src/DEBIAN/control
> +Depends: libibverbs-dev (>= 17.1-1ubuntu0.2), librdmacm-dev (>= 17.1-1ubuntu0.2), libjsonrpccpp-dev (>= 0.7.0-1build2), libjsoncpp-dev (>= 1.7.4-3), libyaml-cpp-dev (>= 0.5.2-4ubuntu1), libtbb-dev (>
, autogen (>= 5.18.12-4), yasm (>= 1.3.0-2build1), nasm (>=2.13.02-0.1), libboost-all-dev (>=1.65.1.0ubuntu1),
이 부분은 기존 isa-l 라이브러리를 직접 빌드할 때 필요했을 것 같은 패키지로 보입니다. 따라서 libisal-dev 를 제외하고는 제거되어도 큰 문제가 없을 것 같습니다.

2022-06-21 06:01 UTC, Seochokid commented on script/pkgdep.sh
> +    apt install -y autogen yasm nasm libboost-all-dev libisal-dev
이 부분도 마찬가지로 libisal-dev 외에는 제거되어도 괜찮지 않을까요?

2022-06-21 06:17 UTC, junghyun-34 commented on package/src/DEBIAN/control
> +Depends: libibverbs-dev (>= 17.1-1ubuntu0.2), librdmacm-dev (>= 17.1-1ubuntu0.2), libjsonrpccpp-dev (>= 0.7.0-1build2), libjsoncpp-dev (>= 1.7.4-3), libyaml-cpp-dev (>= 0.5.2-4ubuntu1), libtbb-dev (>
직접 빌드하지 않을 경우 libisal-dev만 필요한 것 확인 후 커멘트 반영하였습니다. 감사합니다 👍

2022-06-21 06:17 UTC, junghyun-34 commented on script/pkgdep.sh
> +    apt install -y autogen yasm nasm libboost-all-dev libisal-dev
커멘트 반영하였습니다. 감사합니다 👍

2022-07-01 10:16 UTC, closed without merging