Awibof 6255 sds
poseidonos/poseidonos pull request #138
Opened 2022-06-16 06:13 UTC by manim777

Add Array/Volume usage telemetry metrics

2022-06-16 06:41 UTC, yyu-nim reviewed
수고 많으셨습니다! 코멘트만 확인하고 approve 하겠습니다 감사합니다

2022-06-16 06:41 UTC, yyu-nim commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +    }
혹시 else if 로 MT_COUNTER 타입일 경우에 대해서는 SetCounterValue() 를 해줄수 있도록 추가되는 것은 어떨까요?? (혹시 의도적으로 gauge type 만 이 method를 쓸 수 있게 강제하는 것이 아니라면...)

2022-06-16 06:41 UTC, yyu-nim commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +AddUsageMetric(POSMetricVector* posMetricVector,
line 162 에 있는 AddUsageMetric() 이랑 비슷해보이는데 혹시 의도된 부분일지 확인 부탁드릴께요

2022-06-16 06:41 UTC, yyu-nim commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +PublishTimeTriggeredMetric(POSMetricVector* posMetricVector)
이 부분도 혹시 동일 함수가 들어간 것인지 확인 부탁드리겠습니다

2022-06-16 06:44 UTC, manim777 commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +    }
기존 telemetry_air_delegator 함수와 style을 맞추려고 기 코드와 같이 수정하긴 했는데요 Count 값도 받을수 있도록 바꾸겠습니다.

2022-06-16 06:44 UTC, manim777 commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +AddUsageMetric(POSMetricVector* posMetricVector,
헉.. 머지가 잘못된 것 같습니다! 수정하도록 하겠습니다. ㅠ

2022-06-16 06:45 UTC, manim777 commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +PublishTimeTriggeredMetric(POSMetricVector* posMetricVector)
헛 이 부분도 머지가 잘못되서 같이 들어간 것 같습니다. 수정하겠습니다

2022-06-16 07:20 UTC, yyu-nim commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +    }
확인 감사합니다!

2022-06-16 07:37 UTC, manim777 reviewed
review 반영 및 rebase + conflict 해소 입니다.

2022-06-16 07:44 UTC, manim777 commented
> 

와.. 이거 어렵네요 @@ 제대로 하고 있는건지 모르겠습니다 ㅋㅋㅋ review resolve도 제가 했는데 제가 하는 거 맞나요? 영진님 코멘트 보니까 리뷰 작성자가 resolve 했었어야 했던 게 아닌가 싶기도 하고 ㅠㅠ

2022-06-16 07:47 UTC, yyu-nim submitted a review, later dismissed

2022-06-16 08:22 UTC, isaac-baek commented on src/volume/volume_manager.cpp
> +    if (tp == nullptr)
line 85~93 과 중복되는 내용인거 같은데요 확인부탁드립니다.

2022-06-16 08:27 UTC, manim777 commented on src/volume/volume_manager.cpp
> +    if (tp == nullptr)
넵 rebase 하면서 중복되어 수정 커밋 준비중입니다. ㅠ

2022-06-16 09:06 UTC, manim777 commented on src/volume/volume_manager.cpp
> +    if (tp != nullptr)
넵 rebase 하면서 중복되어 수정 커밋 준비중입니다. ㅠ

2022-06-16 10:34 UTC, so931 reviewed
수고하셨습니다!

2022-06-16 10:34 UTC, so931 commented on src/telemetry/telemetry_air/telemetry_air_delegator.cpp
> +PublishTimeTriggeredMetric(POSMetricVector* posMetricVector)
@mmschoi 여기 진희님 구현하신 부분이 지금 문성님 구현하려고 하신 부분이랑 동일한 것 같습니다. 리뷰해주시면 좋을 것 같네요!

2022-06-16 10:34 UTC, so931 commented on src/telemetry/telemetry_id.h
> +static const std::string TEL60002_ARRAY_USAGE_BLK_CNT = "array_usage_cnt";
60002, 60003 항목에 대해서 Metrics.md에도 같이 추가해주시면 좋을 것 같습니다!

2022-06-16 10:34 UTC, so931 commented on src/mapper/map/map_header.cpp
> +    publishCode = (mapId << UINT8_WIDTH) + arrayId;
이 변수는 사용하는 곳이 없는 것 같은데 빠진걸까요? 아니면 제가 못찾은건지 ㅎㅎ

2022-06-16 11:10 UTC, yyu-nim submitted a review, later dismissed

2022-06-17 01:06 UTC, manim777 commented on src/telemetry/telemetry_id.h
> +static const std::string TEL60002_ARRAY_USAGE_BLK_CNT = "array_usage_cnt";
추가하겠습니다

2022-06-17 01:07 UTC, manim777 commented on src/mapper/map/map_header.cpp
> +    publishCode = (mapId << UINT8_WIDTH) + arrayId;
헛 publish 하는 위치를 옮겼는데 흔적이 남은것 같습니다 제거할게요

2022-06-17 06:07 UTC, so931 requested changes
수고하셨습니다!

2022-06-17 06:07 UTC, so931 submitted a review, later dismissed

2022-06-17 09:28 UTC, MunseopLim approved these changes
수고하셨습니다. 최근에 들어간 모듈까지 야무지게 쓰셨네요 ㅎㅎ

2022-06-17 10:03 UTC, merged