[AWIBOF-6440] Clean up trace
poseidonos/poseidonos pull request #166
Opened 2022-06-24 05:05 UTC by mmschoi

- flow control
- resource checker

Signed-off-by: mms.choi <mms.choi@samsung.com>

2022-06-24 05:07 UTC, mmschoi commented on src/gc/flow_control/flow_control.h
> +    uint32_t freeSegments = 0;
free segment count를 tracking하기 위해 member 변수로 추가 하고, INFO로 TRACE 남깁니다.

2022-06-24 05:08 UTC, mmschoi commented on src/include/pos_event_id.h
> +        {(int)POS_EVENT_ID::MBR_ABR_GET_LIST_SUCCESS,
EID 중복으로 변경 합니다.

2022-06-24 05:16 UTC, mjlee34 commented on src/resource_checker/resource_checker.cpp
> +        "running count:{}", runningCnt);
미래에 혹시 모를 파싱을 위해서 running count -> running_count 처럼 공백없는 이름을 제안드립니다.

2022-06-24 05:17 UTC, mjlee34 commented on src/resource_checker/resource_checker.cpp
> +        "running count:{}", runningCnt);
여기도 부탁드리겠습니다.

2022-06-24 05:17 UTC, mjlee34 commented on src/resource_checker/resource_checker.cpp
> +        "thread id={}, enable={}",
여기도 공백을 제거 부탁드리고 = 대신에 : 로 부탁드립니다.

2022-06-24 05:19 UTC, mjlee34 commented on src/include/pos_event_id.h
> +                "Start periodic resource checking.", "", "")},
Event 정보 메시지는 Event를 잘 설명하는 문장(주어 + 동사 + (목적어))으로 구성되어야 합니다. log_management.md 파일 참고해서 작성을 부탁드리겠습니다.

Log만 보고도 상황을 파악할 수 있도록 구체적으로 기술 부탁드리겠습니다.

2022-06-24 05:21 UTC, mjlee34 commented on src/include/pos_event_id.h
> +        {(int)POS_EVENT_ID::FC_FORCERESET_DONE,
향후 Log 가독성을 위해 FC 대신 FLOW_CONTROL 풀네임을 쓰는건 어떨까요? FC가 Fibre Channel 등과 혼선을 줄 수 있을 것 같습니다. 😃

2022-06-24 05:22 UTC, mjlee34 commented on src/include/pos_event_id.h
> +                "Force set.", "", "")},
예시를 하나 드리면, 제 생각에는 "Flow control has been started forcefully." 등으로 구체적으로 적어주시면 좋을 것 같습니다. 😃

2022-06-24 05:22 UTC, hsung-yang approved these changes
LGTM
명준님 코멘트 반영하시고 넣으시면 될 것 같습니다

2022-06-24 05:23 UTC, mjlee34 requested changes
고생하셨습니다. 커멘트 확인 부탁드리겠습니다. :)

2022-06-24 06:08 UTC, mmschoi commented on src/resource_checker/resource_checker.cpp
> +        "running count:{}", runningCnt);
네 반영하겠습니다.

2022-06-24 06:19 UTC, mmschoi commented on src/include/pos_event_id.h
> +                "Force set.", "", "")},
Logic기준으로 보니, forced reset을 위한 timeout을 설정 동작 입니다.
아래와 같이 반영 하겠습니다.
"Set the timeout for forced token reset"

2022-06-24 06:26 UTC, mmschoi commented on src/include/pos_event_id.h
> +        {(int)POS_EVENT_ID::FC_FORCERESET_DONE,
좋은 의견 감사합니다. 반영 하도록 하겠습니다.

2022-06-24 07:06 UTC, mmschoi commented on src/resource_checker/resource_checker.cpp
> +        "runnrunning_countingCount:{}", runningCnt);
Need to fix

2022-06-28 06:56 UTC, ringopow submitted a review, later dismissed

2022-06-28 06:58 UTC, mjlee34 commented on src/gc/flow_control/flow_control.cpp
> +        POS_TRACE_DEBUG(EID(FLOW_CONTROL_NEGATIVE_TOKEN), "FlowControl GetToken should be greater than or equal to zero token:{}", token);
PoseidonOS에서 Event는 "State 변화에 대한 시도" 로 정의하고 있습니다. 따라서 Event 이름을 붙여주실 때 이를 고려해서 시도, 성공, 실패의 명사로 끝나도록 부탁드리겠습니다. 번거로우시겠지만 향후 Log 가독성을 위해 부탁드리겠습니다. 😃

2022-06-28 06:59 UTC, mjlee34 commented on src/gc/flow_control/flow_control.cpp
> +            POS_TRACE_INFO(EID(FLOW_CONTROL_RESET_FORCERESET),
예를 들어, 여기도 EVENT 이름만 보고 어떤 동작이 수행되었는지 알기가 어려운 것 같습니다. 다른 이름들 참고해서 작명 부탁드리겠습니다.^^;;

2022-06-28 07:00 UTC, mjlee34 commented on src/resource_checker/resource_checker.cpp
> +            "Thread id:{}", std::hash<std::thread::id>{}(th->get_id()));
향후 파싱 가능성을 위해 공백이 없으면 더 좋을 것 같습니다.

2022-06-28 07:01 UTC, mjlee34 requested changes
고생 많으셨습니다. EVENT 이름 작명이 조금 개선되면 좋을 것 같습니다. 의견 검토해주시고 반영 부탁드립니다. 😄

2022-06-28 07:09 UTC, minjoon-ahn approved these changes
LGTM

2022-06-28 07:10 UTC, mmschoi commented on src/gc/flow_control/flow_control.cpp
> +        POS_TRACE_DEBUG(EID(FLOW_CONTROL_NEGATIVE_TOKEN), "FlowControl GetToken should be greater than or equal to zero token:{}", token);
Prefix만을 변경 하여, 이름에 대한 고민은 하지 않았습니다. logic 기준으로 한번 작명을 해보겠습니다.

2022-06-28 07:10 UTC, mmschoi commented on src/gc/flow_control/flow_control.cpp
> +            POS_TRACE_INFO(EID(FLOW_CONTROL_RESET_FORCERESET),
위와 동일 합니다.

2022-06-28 07:10 UTC, mmschoi commented on src/resource_checker/resource_checker.cpp
> +            "Thread id:{}", std::hash<std::thread::id>{}(th->get_id()));
'_'가 빠졌군요~ 감사합니다.

2022-06-28 08:40 UTC, mjlee34 approved these changes
고생하셨습니다. 요청을 많이 드려 죄송합니다 :)

2022-06-28 08:53 UTC, mjlee34 approved these changes

2022-06-28 08:53 UTC, ringopow approved these changes

2022-06-28 10:48 UTC, mjlee34 approved these changes

2022-06-28 10:49 UTC, hsung-yang approved these changes
LGTM

2022-06-28 10:50 UTC, merged