Feature/awibof 6450 add monitoring stack to debian package
poseidonos/poseidonos pull request #169
Opened 2022-06-24 08:39 UTC by dshwpark

2022-06-24 08:51 UTC, dshwpark commented on package/src/DEBIAN/control
> +Version: 0.11.0-rc6-+
이부분을 수정한 적이 없는데 맞는지 모르겠네요 ㅠ

2022-06-24 11:24 UTC, next0262 commented on config/pos-prometheus.yml
> +scrape_configs:
scrape가 뭔가요?

2022-06-26 22:54 UTC, dshwpark commented on config/pos-prometheus.yml
> +scrape_configs:
prometheus가 exporter로부터 metric을 pull하는 것을 scrape라고 합니다~

2022-06-26 23:40 UTC, dshwpark commented on tool/ipmi_exporter/LICENSE
> +The MIT License
MIT License를 포함하는 ipmi_exporter를 함께 배포해도 문제가 되지 않을지 고견 부탁드립니다.

2022-06-27 00:17 UTC, Seochokid commented on package/src/DEBIAN/control
> +Version: 0.11.0-rc6-+
패키지 Makefile에 ${POS_VERSION}-${YY}${MM}${DD}${hh}${mm}+${PKG_VERSION} 이 부분으로 패키지버전에 자동으로 커밋 date랑 hash 포함시켜주는 부분이 있습니다.
아마 git log를 제대로 못 읽어와서 커밋 date랑 hash가 반영이 안된 것 같습니다.

2022-06-27 01:02 UTC, madcatlove reviewed
ipmi-exporter 바이너리가 첨부되어있는데
혹시 얘 실행하기 위한 runtime shared library 같은거 필요한게 뭐가 있을까요?

2022-06-27 01:11 UTC, dshwpark commented
> ipmi-exporter 바이너리가 첨부되어있는데 혹시 얘 실행하기 위한 runtime shared library 같은거 필요한게 뭐가 있을까요?

binary 하나만 필요합니다.

2022-06-27 01:13 UTC, dshwpark commented on package/src/DEBIAN/control
> +Version: 0.11.0-rc6-+
살펴보니 got log가 제대로 동작하는 환경에서 Package를 만든다면 sed로 대체될 부분이라 이렇게 해서 commit 한다해도 별 상관이 없겠죠?

2022-06-27 01:48 UTC, so931 requested changes
구두로 논의한 것처럼 IPMI-Exporter에 대한 내용은 분리해야 할 것 같습니다.
prometheus 관련된 내용만 추가 부탁드립니다!

2022-06-27 02:20 UTC, dshwpark commented
> 구두로 논의한 것처럼 IPMI-Exporter에 대한 내용은 분리해야 할 것 같습니다. prometheus 관련된 내용만 추가 부탁드립니다!

네 ipmi-exporter 관련 feature 삭제 했습니다.

2022-06-27 04:34 UTC, so931 approved these changes

2022-06-27 04:54 UTC, merged