[AWIBOF-6753] Adds configuration module(otlp_trace) for trace exporter and enables otlp-exporter
poseidonos/poseidonos pull request #271
Opened 2022-08-17 09:32 UTC by dshwpark

- pos.conf를 통해 trace on/off 및 endpoint 설정 가능
- trace on일 경우, otlp-exporter가 동작

2022-08-17 21:45 UTC, so931 requested changes
추가한 것에 대한 UT도 같이 반영 부탁 드립니다~!

2022-08-17 21:45 UTC, so931 commented on config/pos.conf
> +    "otlp_trace": {
otlp를 제외하고 그냥 trace만 쓰는건 어떨까요? trace 기능에 대한 on/off면 될 것 같고 otlp라는 프로토콜을 굳이 사용자가 알아야 하나? 라는 생각이 듭니다ㅎㅎ

2022-08-17 21:45 UTC, so931 commented on config/pos.conf
> +        "collector_endpoint": "http://localhost:3418/v1/traces"
collector가 아니라 exporter 인거죠?

2022-08-17 21:45 UTC, so931 commented on src/main/poseidonos.cpp
> +Poseidonos::_InitTraceExporter()
외부에 대한 참조가 많아 보이는데 별도 클래스로 분리하는게 어떨까요? 그래야 테스트 작성하기도 쉬울 것 같다는 생각이 드네요 ㅎㅎ

2022-08-17 21:45 UTC, so931 commented on src/main/poseidonos.cpp
> +                    {"service.name", _GetProcName().c_str()},
이 부분은 보통 프로세스명으로 쓰는건가요?
별도 이름 넣기보다 프로세스명과 버전 가져오도록 구현하신거 좋아보이네요 ㅎㅎ

2022-08-17 22:46 UTC, madcatlove commented on src/main/poseidonos.cpp
> +    procName = names.back();
백터의 마지막 값 가져오는게 목적이면 굳이 벡터에 push하지 않고
getline으로 루프 돌다가 탈출 시점에 이미 마지막 값을 getline()이 반환했을테니 그대로 쓰면 어떨까요.
`
while(std::getline(ss,token,'/')) { ; }
procName = token 
`
정도로 마무리 할 수 있지 않을까요

2022-08-17 22:48 UTC, madcatlove commented on src/main/poseidonos.cpp
> +        namespace exporter  = opentelemetry::exporter;
namespace로 분리한 이유가 있을까요?
아래 사용하시는 형태가 using 키워드가 좀 더 적합해보여서요

2022-08-17 23:35 UTC, madcatlove commented on src/main/poseidonos.cpp
> +                auto otlp_http_exporter = std::unique_ptr<sdktrace::SpanExporter>(new exporter::otlp::OtlpHttpExporter(opts));
소스코드 다른곳들은 대부분 변수명을 카멜케이스로 작성하고있는데, 맞춰주시면 좋을 것 같습니다.

2022-08-18 00:41 UTC, dshwpark commented on config/pos.conf
> +    "otlp_trace": {
[poseidonos, poseidonos-cli, etc] -> collector -> user backend 로 span data가 흐를테니 사용자는 collector exporter의 protocol만 알면 되겠네요.
oltp_trace -> trace로 수정하겠습니다.

2022-08-18 00:42 UTC, dshwpark commented on config/pos.conf
> +        "collector_endpoint": "http://localhost:3418/v1/traces"
exporter가 능동적으로 backend(collector)에 push하는 형태이기 때문에 collector가 맞습니다.

2022-08-18 00:44 UTC, dshwpark commented on src/main/poseidonos.cpp
> +Poseidonos::_InitTraceExporter()
네.
이후 AIR처럼 Macro 형태로 instrumentation이 가능하도록 다른 class를 따로 분리하려 했습니다.
Test도 이때 작성하는 건 어떨까 합니다.

2022-08-18 00:47 UTC, so931 commented on config/pos.conf
> +    "otlp_trace": {
확인 감사합니다~~

2022-08-18 00:48 UTC, so931 commented on config/pos.conf
> +        "collector_endpoint": "http://localhost:3418/v1/traces"
아 전송할 endpoint 이군요 이해했습니다 확인 감사합니다~

2022-08-18 00:49 UTC, dshwpark commented on src/main/poseidonos.cpp
> +    procName = names.back();
오 더 깔끔한 방법이네요.
반영하겠습니다.

2022-08-18 00:50 UTC, dshwpark commented on src/main/poseidonos.cpp
> +        namespace exporter  = opentelemetry::exporter;
C++ Instrumentation 예제를 참고하다 보니 이렇게 됐네요.
using은 class 분리 이후 고려해보겠습니다.

2022-08-18 00:51 UTC, dshwpark commented on src/main/poseidonos.cpp
> +                auto otlp_http_exporter = std::unique_ptr<sdktrace::SpanExporter>(new exporter::otlp::OtlpHttpExporter(opts));
넵.
이 부분 역시 class 분리 이후 카멜케이스로 작성하겠습니다.

2022-08-18 00:53 UTC, so931 commented on src/main/poseidonos.cpp
> +    Poseidonos::_SetProcName(argv[0]);
여기 SetProcName 호출만 Poseidonos class를 명시한 이유가 있을까요? 다른데랑 중복되는데가 있는지요??

2022-08-18 00:59 UTC, so931 commented on src/main/poseidonos.cpp
> +Poseidonos::_InitTraceExporter()
아 넵 클래스 분리는 나중에 하더라도 테스트는 같이 추가되었으면 합니다.
특히 main 부분이라 다른 변경점이 들어올 가능성도 있고 이때 깨질 수 있을 것 같네요. 다른 테스트 추가는 해야할 작업이 많으니 UT 정도만 해도 될 것 같습니다. 말씀하신 구현 내용이 다 들어올 시점에는 UT가 아니라 Integration/System Test 정도가 CI Plan에 추가 되는 것도 좋을 것 같고요~~

2022-08-18 01:01 UTC, dshwpark commented on src/main/poseidonos.cpp
> +                    {"service.name", _GetProcName().c_str()},
네 맞습니다~

2022-08-18 01:04 UTC, dshwpark commented on src/main/poseidonos.cpp
> +Poseidonos::_InitTraceExporter()
네 UT 추가하겠습니다.

2022-08-18 01:05 UTC, dshwpark commented on src/main/poseidonos.cpp
> +    Poseidonos::_SetProcName(argv[0]);
conflict은 없습니다.
class 명 제거 하겠습니다.

2022-08-22 01:36 UTC, next0262 commented
OTel go의 context와 같은 존재가 OTel C++에도 있나요?

2022-08-22 01:38 UTC, next0262 commented on test/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "--coverage -ftest-coverage -fpermissive -fPIC -pthread")
저번에 말씀해주셨던 pthread 설정이 이부분이죠?

2022-08-22 01:38 UTC, next0262 commented on src/trace/trace_exporter.cpp
> +void
OTel go의 context와 같은 존재가 OTel C++에도 있나요?

2022-08-22 03:46 UTC, madcatlove commented on src/main/poseidonos.cpp
> +                TraceExporterSingleton::Instance()->Init(serviceName, serviceVersion, traceEndPoint);
Init() 함수에서 bool 형태로 Enabled 여부를 리턴해주게되면
IsEnabled() 가 필요 없어질 것 같은데요. 혹시 향후에 IsEnabled()를 사용할 계획이 있는건가요?

2022-08-22 07:26 UTC, Seochokid commented on src/trace/trace_exporter.h
> +    void _Enable(void);
따로 Disable 해주는 메소드는 없는건가요?

2022-08-22 10:25 UTC, dshwpark commented on src/main/poseidonos.cpp
> +                TraceExporterSingleton::Instance()->Init(serviceName, serviceVersion, traceEndPoint);
향후 IsEnabled()를 통해 Instrumentation된 code가 trace data를 낼지 말지 결정할 예정입니다.

2022-08-22 10:25 UTC, dshwpark commented on src/trace/trace_exporter.h
> +    void _Enable(void);
향후 CLI를 통해 Dynamic하게 disable하는 것이 가능해질 때 추가할 예정입니다.

2022-08-22 10:26 UTC, dshwpark commented on test/CMakeLists.txt
> +set(CMAKE_CXX_FLAGS "--coverage -ftest-coverage -fpermissive -fPIC -pthread")
네 맞습니다.

2022-08-22 10:27 UTC, dshwpark commented on src/trace/trace_exporter.cpp
> +void
아직 확인은 하지 못했는데, context를 baggage로 전달해줄 경우 비슷한 기능을 하도록 추가할 예정입니다.

2022-08-31 01:28 UTC, Seochokid approved these changes
conf 파일을 통해 쉽게 on/off나 endpoint 설정이 가능해지니 좋은 것 같습니다.

2022-08-31 03:11 UTC, so931 approved these changes
수고하셨습니다! 혹시 시간나실때 comment 등록한것 확인만 부탁드립니다~!

2022-08-31 03:11 UTC, so931 commented on Makefile
> +DEFINE += -DHAVE_ABSEIL
아 이게 해결책이였군요!

2022-08-31 03:11 UTC, so931 commented on lib/CMakeLists.txt
> +    CONFIGURE_COMMAND cmake ${PROJ_ROOT}/lib/${POS_DEP_OTEL} -DBUILD_TESTING=OFF -DWITH_OTLP=ON -DWITH_ABSEIL=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX:PATH=${PROJ_ROOT}/lib/${PO
With ABSEIL과 POSITION INDPENDENT CODE 두개 다를 해줘야 했던건가요?

2022-08-31 03:47 UTC, dshwpark commented on Makefile
> +DEFINE += -DHAVE_ABSEIL
넵~ㅎㅎ

2022-08-31 03:51 UTC, dshwpark commented on lib/CMakeLists.txt
> +    CONFIGURE_COMMAND cmake ${PROJ_ROOT}/lib/${POS_DEP_OTEL} -DBUILD_TESTING=OFF -DWITH_OTLP=ON -DWITH_ABSEIL=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX:PATH=${PROJ_ROOT}/lib/${PO
WITH_ABSEIL=ON은 system absl을 사용하겠다는 의미이고 -DCMAKE_POSITION_INDEPENDENT_CODE=ON은 공유 라이브러리를 생성하겠다는 의미인데요.

전자는 Makefile의 HAVE_ABSEIL과 함께 사용해야 하고
후자는 ibofos_library 사용과 관련되어 필요합니다.

2022-08-31 03:51 UTC, merged

2022-09-02 04:51 UTC, next0262 commented on test/unit-tests/trace/otlp_factory_mock.h
> +    MOCK_METHOD(exporter::otlp::OtlpHttpExporter *, CreateOtlpHttpExporter, (exporter::otlp::OtlpHttpExporterOptions opt), (override));
이게 어떤 의미인가요?