[AWIBOF-6660] Enable Samsung extended smart log information
poseidonos/poseidonos pull request #274
Opened 2022-08-18 05:22 UTC by mmschoi

Signed-off-by: mms.choi <mms.choi@samsung.com>

2022-08-18 05:24 UTC, mmschoi commented on config/publication_list_default.yaml
> -  soft_media_error_low:
lower, upper로 통일 하였습니다.

2022-08-18 05:25 UTC, mmschoi commented on doc/development/telemetry/METRICS.md
> +  - [_**lifetimeWaf**_](#lifetimewaf)
Samsung Ext. smart에 포함된 metric 전체 metric은 아니고 중복등의 metric을 제외한 항목들을 추가 하였습니다.

2022-08-18 05:27 UTC, mmschoi commented on src/cli/command_processor.cpp
> +    SmartReturnType ret = smartCollector->CollectPerCtrl(&payload, ctrlr, SmartReqId::NVME_HEALTH_INFO);
현재는 cli를 통해서 NVME_HEALTH_INFO까지만 받아 올 수 있습니다.
Cli를 통해 OCP, Ext. Smart 정보를 가져오기 위해서는 추가 작업이 필요 합니다.

2022-08-18 05:38 UTC, mmschoi commented on src/device/unvme/unvme_cmd.cpp
> +                    (pageContext->lid == SPDK_NVME_LOG_EXTENDED_SMART))
Ext smart LID 추가

2022-08-18 05:38 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +  supportedExtSmart(false)
extended smart 지원 여부를 구분하기 위한  boolean flag입니다.

2022-08-18 05:39 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +    property->fr = _GetFR();
firmware version으로 samsung device 중 General FW 구분을 위해 추가 되었습니다.

2022-08-18 05:41 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +UnvmeSsd::_GetFR()
기 구현된 function을 참고 했으나, private function들을 보면 동일 admin command를 여러번 수행하여 각각의 정보를 가져오고 있습니다. 추후에는 하나의 command만 던지고 각각 필요한 정보를 private variable에 저장하는 방식이 좋을 것 같습니다.

2022-08-18 05:41 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +    if ((property->mn.find("SAMSUNG") != string::npos) && (property->fr.substr(5,1) == "0"))
Samsung & General fw인 경우에만 supperted Ext smart가 true로 셋팅 됩니다.

2022-08-18 05:42 UTC, mmschoi commented on src/resource_checker/smart_collector.cpp
> +        if (0 == CollectGetLogPage(payload, ctrlr, device.name, SmartReqId::NVME_HEALTH_INFO))
Get log page로 복수의 LID 지원을 위해 변경 되었습니다.

2022-08-18 05:42 UTC, mmschoi commented on src/resource_checker/smart_collector.cpp
> +                if (0 == CollectGetLogPage(extPayload, ctrlr, device.name, SmartReqId::EXTENDED_SMART_INFO))
Samsung extended smart를 가져오는 부분입니다.

2022-08-18 05:46 UTC, mmschoi commented
spdk library update를 위한 code review 중입니다. review 완료되면 spdk patch update와 함께 pre-commit 정상 수행 될 것으로 기대 합니다. (spdk PR : http://10.227.30.176:8060/cru/CR-IBOF-SPDK-25)

2022-08-22 03:47 UTC, mmschoi commented on lib/spdk-22.01.1.patch
> +diff --git include/spdk/nvme_spec.h include/spdk/nvme_spec.h
extended smart와 ocp 추가로 인해 변경 되었습니다.

2022-08-22 05:41 UTC, hsung-yang commented on src/device/unvme/unvme_cmd.cpp
> +                    (pageContext->lid == SPDK_NVME_LOG_EXTENDED_SMART))
LID가 로그 아이디인가요?

2022-08-22 05:43 UTC, hsung-yang commented on src/device/unvme/unvme_ssd.cpp
> +    property->fr = _GetFR();
FR은 Firmware Revision인가요?

2022-08-22 05:46 UTC, hsung-yang commented on doc/development/telemetry/ID_RULES.md
110016~110019는 Reserved Number인가요?

2022-08-22 05:48 UTC, hsung-yang submitted a review, later dismissed
LGTM

2022-08-22 06:27 UTC, mmschoi commented on src/device/unvme/unvme_cmd.cpp
> +                    (pageContext->lid == SPDK_NVME_LOG_EXTENDED_SMART))
네, 맞습니다. Log identifier 의 약자 입니다.

2022-08-22 06:27 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +    property->fr = _GetFR();
네 맞습니다.

2022-08-22 06:27 UTC, mmschoi commented on doc/development/telemetry/ID_RULES.md
네~ extended smart와 구분을 짓고 싶어 rsvd로 빼 놓았습니다.

2022-08-22 06:46 UTC, mjlee34 commented on src/device/unvme/unvme_ssd.cpp
> +  supportedExtSmart(false)
이름을 조금 더 명확하게 isExtSmartSupported 로 바꾸는건 어떨까요?

2022-08-22 06:48 UTC, mjlee34 commented on src/device/unvme/unvme_ssd.cpp
> +    if ((property->mn.find("SAMSUNG") != string::npos) && (property->fr.substr(5,1) == "0"))
코드만 봐서는 "0" 의 의미가 General FW인지 알 수 없을 것 같습니다.

#define GENERAL_FIRMWARE "0"
...
property->fr.substr(5,1) == GENERAL_FIRMWARE

식으로 변경하면 좋을 것 같습니다. :)

2022-08-22 06:49 UTC, mjlee34 requested changes
고생하셨습니다. 커멘트 확인만 부탁드립니다. 👍

2022-08-22 07:24 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +    if ((property->mn.find("SAMSUNG") != string::npos) && (property->fr.substr(5,1) == "0"))
매의 눈 이시군요.. ㅎㅎ 숨길까 말까 한 코드라 0으로 했는데 define 추가 해도 괜찮다면 더 나을것 같아요.

2022-08-22 07:27 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +  supportedExtSmart(false)
아~ 좋습니다~ "Is" 추가 하겠습니다 :)

2022-08-29 03:59 UTC, mjlee34 approved these changes
LGTM 고생하셨습니다 :)

2022-08-29 04:07 UTC, minjoon-ahn approved these changes

2022-08-29 04:34 UTC, mmschoi commented on src/device/unvme/unvme_ssd.cpp
> +        (property->fr.substr(5, 1) == GENERAL_FIRMWARE))
firmware name이 정상적이지 않은경우 seg fault의 위험이 있어 length check 코드 반영 하겠습니다.

2022-08-30 03:55 UTC, junghyun-34 approved these changes
LGTM

2022-08-30 05:22 UTC, mjlee34 approved these changes
고생하셨습니다

2022-08-30 06:28 UTC, merged