[AWIBOF-6789] system info instrumentation
poseidonos/poseidonos pull request #303
Opened 2022-08-29 08:05 UTC by next0262

- add otelmgr & tracer and enabling flag

- otelEnable is set as false

2022-08-29 08:34 UTC, mjlee34 commented on tool/cli/cmd/root.go
> +	err := otelmgr.GetOtelManagerInstance().InitTracerProvider(context.Background(), "poseidonos-cli", getVersion())
향후 변경 용이성을 위해 "poseidonos-cli" 와 같은 string들은 globals/strings.go 에 정의해서 사용하면 좋을 것 같습니다. 😃

2022-08-29 08:34 UTC, mjlee34 commented on tool/cli/cmd/systemcmds/system_info.go
> +		t.SetTrace(m.GetRootContext(), "systemcmds", "systeminfocmd")
여기 command 이름들도 globals/strings.go에 정의하면 좋을 것 같습니다.

2022-08-29 08:36 UTC, mjlee34 commented on tool/cli/lib/pnconnector/src/util/resource.go
> -	info := bindataFileInfo{name: "../resources/events.yaml", size: 37766, mode: os.FileMode(420), modTime: time.Unix(1635316153, 0)}
이 파일은 항상 골칫덩이인데, 빌드시 자동 생성되는 파일입니다.
커밋에서 제외 부탁드리겠습니다. 😃

2022-08-29 08:38 UTC, mjlee34 requested changes
고생하셨습니다. 몇몇 커멘트 반영만 부탁드립니다.

앞으로 모든 커맨드에 이 커밋과 같은 코드가 추가되나요? 

반복작업이 많을 것 같은데,
만약 CLI 코드를 조금 더 효율적으로 리팩토링하면 작업량도 줄까요?
리팩토링 고민이 많습니다.

의견 주시면 감사하겠습니다.

2022-08-31 01:25 UTC, dshwpark commented
LGTM!
CI가 제대로 돌지 않는 것만 해결해주시면 될 것 같습니다.
이후 POS를 Tracing 시 request(CLI→POS)에 context를 싣는 protocol을 함께 논의해보아요~

2022-09-06 09:47 UTC, next0262 commented on tool/cli/cmd/root.go
> +	err := otelmgr.GetOtelManagerInstance().InitTracerProvider(context.Background(), "poseidonos-cli", getVersion())
조언 주신대로 strings.go에 따로 입력하였습니다!

2022-09-06 09:47 UTC, next0262 commented on tool/cli/cmd/systemcmds/system_info.go
> +		t.SetTrace(m.GetRootContext(), "systemcmds", "systeminfocmd")
위와 동일합니다!

2022-09-06 09:47 UTC, next0262 commented on tool/cli/lib/pnconnector/src/util/resource.go
> -	info := bindataFileInfo{name: "../resources/events.yaml", size: 37766, mode: os.FileMode(420), modTime: time.Unix(1635316153, 0)}
제외하였습니다!

2022-09-06 09:50 UTC, next0262 commented
> 고생하셨습니다. 몇몇 커멘트 반영만 부탁드립니다.
> 
> 앞으로 모든 커맨드에 이 커밋과 같은 코드가 추가되나요?
> 
> 반복작업이 많을 것 같은데, 만약 CLI 코드를 조금 더 효율적으로 리팩토링하면 작업량도 줄까요? 리팩토링 고민이 많습니다.
> 
> 의견 주시면 감사하겠습니다.

네넵!  grpcmgr.go 같은 경우 보면 각 함수가 거의 비슷한 형태이긴 하더라구요. 하나의 함수로 합치면 tracing 량을 많이 줄일 수 있을것으로 예상은 되나 가독성 측면에서 옳은지는 고민을 좀 해봐야할거 같습니다. 고민해보고 의견드려보도록 하겠습니다!

2022-09-07 00:44 UTC, dshwpark approved these changes

2022-09-07 01:12 UTC, mjlee34 approved these changes
고생하셨습니다 👍

2022-09-07 01:36 UTC, next0262 commented
pos-exporter 관련해서 일단 go test가 동작하도록 수정(pb import path를 /api/pos.metric에서 /api로 바꿈)하였고, 모두 Pass하는 것 확인하였습니다!

2022-09-07 02:54 UTC, madcatlove approved these changes
수고하셨습니다!

2022-09-07 03:48 UTC, dshwpark approved these changes

2022-09-07 04:46 UTC, merged