[AWIBOF-5960] add pos debian package artifact upload action script
poseidonos/poseidonos pull request #42
Opened 2022-05-10 06:21 UTC by Seochokid

72시간 테스트가 성공으로 끝나면 POS 데비안 패키지를 아티팩트로 업로드하는 액션 스크립트 작성

2022-05-10 06:26 UTC, madcatlove commented on .github/workflows/package_upload.yml
> +        sudo make package -j8
나중에 이 부분에서 debian package 생성할 때
현재는 commit hash로 version명 생성하지만, 이렇게 되면 CD Pipeline에서 Upgrade 시나리오에서 활용이 어려워져서
Increased Number 같은거로 좀  기존 버전 보다 높다 라는걸 표현하는걸 고민해봐야할거같아요.

2022-05-10 06:32 UTC, Seochokid commented on .github/workflows/package_upload.yml
> +        sudo make package -j8
따로 CD pipeline용 리비전을 관리해야될까요?

2022-05-10 06:54 UTC, next0262 submitted a review, later dismissed

2022-05-10 06:54 UTC, next0262 commented on .github/workflows/package_upload.yml
> +    runs-on: VM
이 후엔 Label을 좀 구분해서, build의 경우엔 Block Device 안 달려있고 Build에 좀 특화된 성능을 보이는 인스턴스 타입이 할당되도록 해야겠네요

2022-05-10 06:57 UTC, next0262 commented
@so931 현진님 reviewer로 추가드렸어요~

2022-05-10 07:16 UTC, so931 commented on .github/workflows/package_upload.yml
> +    runs-on: VM
어짜피 3일 테스트 뒤에 수행하는 과정이라면 패키지 업로드가 길어져도 상관없지 않을까라는 생각이 듭니다. 만약 그렇다면 무료 VM 쓰는것도 괜찮아 보이네요 ㅎㅎ

2022-05-10 08:58 UTC, so931 requested changes

2022-05-10 09:33 UTC, madcatlove commented on .github/workflows/package_upload.yml
> +        sudo make package -j8
CD pipeline을 위해서 따로 리비전 관리까지는 필요없어보이는데요.
혹시 네이밍룰에  debian-revision 이런부분들이 있는데 혹시 commit date를 좀 활용해보면 어떨까요?

가령
0.1.11+YYYYMMDDHOURMIN
**--> 0.1.11+202205101832**

`i  xz-lzma                             5.1.1alpha+20110809-3               XZ-format compression utilities - compatibility commands
ii  xz-utils                            5.1.1alpha+20110809-3               XZ-format compression utilities
ii  zabbix-agent                        1:1.8.11-1                          network monitoring solution - agent
ii  zlib1g                              1:1.2.3.4.dfsg-3ubuntu4             compression library - runtime
ii  zlib1g-dev                          1:1.2.3.4.dfsg-3ubuntu4             compression library - development`

2022-05-10 10:04 UTC, Seochokid commented on .github/workflows/package_upload.yml
> +        sudo make package -j8
0.11.6-YYYYMMDDhhmm+comithash(7자리) 로 구성하면 괜찮을 것 같습니다.
--> 0.11.6-20220510+a5ef453
버전 비교는 0.11.6->YYYYMMDDhhmm->a5ef453 순으로 하니, upgrade 시나리오에서도 큰 문제 없이 최신버전 판별이 가능할 것 같습니다.

2022-05-10 10:06 UTC, Seochokid commented on .github/workflows/package_upload.yml
> +    runs-on: VM
네 큰 차이는 없을 것으로 생각됩니다.

2022-05-10 10:08 UTC, madcatlove commented on .github/workflows/package_upload.yml
> +        sudo make package -j8
예 좋을 것 같습니다.
혹시 이 PR에 반영이 가능할까요?

2022-05-11 00:42 UTC, Seochokid commented on .github/workflows/package_upload.yml
> +        sudo make package -j8
넵 가능할 것 같습니다.

2022-05-11 02:16 UTC, so931 approved these changes

2022-05-11 02:27 UTC, madcatlove commented on package/Makefile
> +	@sed "2s/Version:.*/Version: ${POS_VERSION}-${YY}${MM}${DD}${hh}${mm}+${PKG_VERSION}/g" src/DEBIAN/control -i
오 바로 반영해주셨군요.
덕분에 CD 업그레이드 시나리오에서 큰 문제 없을 것 같네요. 감사합니다.

2022-05-11 02:29 UTC, madcatlove approved these changes

2022-05-11 03:14 UTC, merged

2022-05-17 09:58 UTC, madcatlove commented on .github/workflows/package_upload.yml
> +    runs-on: VM
아 패키징하는데 소요되는 시간은 크게 중요하지 않으니, 무료 Tier을 사용해도 충분해 보이긴 할 것 같습니다.
어짜피 72시간 Plan들 후에 빌드되는거니깐 1~2시간정도는 그냥 기다릴법 할 것 같습니다.
비용 낮추는게 우선이죠 ㅎㅎ

2022-05-17 09:59 UTC, madcatlove commented on .github/workflows/package_upload.yml
> +    runs-on: VM
아마 Block Device는 필요없을거같고, CPU가 좋은 녀석으로 해야 될 것 같아요.
예전에 사내에서 따로 공유드렸던 Instance Type별 Build 속도 보면, 이런 경우에는 CPU 영향이 가장 큽니다.