[AWIBOF-5902] debugging on log upload & add uploading core dump in wo…
poseidonos/poseidonos pull request #44
Opened 2022-05-11 05:34 UTC by next0262

…rkflows

- add timeout to precommit test

2022-05-11 05:41 UTC, next0262 commented
- 72 hour test, long term test, postcommit test에서 pos log에 대한 artifact 업로드가 제대로 수행되지 않는 문제를 고침
- test 실패시 core dump를 artifact로 업로드하도록 추가
- precommit test에 timeout 추가하였습니다.

2022-05-11 06:01 UTC, next0262 commented on .github/workflows/script/clean_backup.sh
> -    rm -rf /var/log/pos/*
이 부분 때문에 log가 삭제되어 업로드가 안되었던 것이었습니다

2022-05-11 07:52 UTC, so931 requested changes

2022-05-11 07:52 UTC, so931 commented on .github/workflows/72_hour.yml
> +      id: three_days
id하고 test 이름을 통일하는건 어떨까요?
name은 72h인데 id는 three_days라 약간 헷갈리네요

2022-05-11 07:52 UTC, so931 commented on .github/workflows/72_hour.yml
> +        name: Three_Days_LOG
여기도 마찬가지로 three_days나 72h로 통일하면 좋을 것 같습니다~!

2022-05-11 07:52 UTC, so931 commented on .github/workflows/postcommit.yml
> +          ${{github.workspace}}/tool/dump/*.tar.gz*
혹시 coredump 생성 위치가 바뀐건가요??

2022-05-11 07:52 UTC, so931 commented on .github/workflows/postcommit.yml
> +  Create_Issue:
이슈 생성하는건 지난 PR에서 말씀드린 것 처럼 정책 결정 이후로 적용하시죠~~

2022-05-11 08:02 UTC, next0262 commented on .github/workflows/72_hour.yml
> +      id: three_days
아 이게 원래 72h로 시도했었는데요. github action 문법상 id에 숫자를 맨앞에 두지 못하게 하는게 있어 오류가 발생합니다. 괜찮은 다른 네이밍있으시면 수정하도록 하겠습니다.

2022-05-11 08:03 UTC, next0262 commented on .github/workflows/72_hour.yml
> +        name: Three_Days_LOG
artifact name은 72hour 로 바꿀 수 있을거 같습니다 이 부분은 수정하겠습니다.

2022-05-11 08:05 UTC, Seochokid commented on .github/workflows/72_hour.yml
> +      id: three_days
전부 three_days 로 통일하는건 어떤가요

2022-05-11 08:09 UTC, next0262 commented on .github/workflows/postcommit.yml
> +  Create_Issue:
이건 실수로 들어갔네요 제거하겠습니다

2022-05-11 08:12 UTC, so931 commented on .github/workflows/72_hour.yml
> +      id: three_days
넵 일단은 통일하는것이 더 중요하다고 생각해서 three_days로 통일해두는것도 괜찮을 것 같습니다~~~

2022-05-11 08:12 UTC, so931 commented on .github/workflows/72_hour.yml
> +        name: Three_Days_LOG
확인 감사합니다!

2022-05-11 08:15 UTC, so931 commented on .github/workflows/postcommit.yml
> +          ${{github.workspace}}/tool/dump/*.tar.gz*
혹시 어디서 경로 확인하셨는지 알 수 있을까요?

2022-05-11 08:23 UTC, next0262 commented on .github/workflows/postcommit.yml
> +          ${{github.workspace}}/tool/dump/*.tar.gz*
.github/workflows/script/clean_backup.sh 여기 입니다

2022-05-11 08:36 UTC, next0262 commented on .github/workflows/72_hour.yml
> +        name: Three_Days_LOG
일단 Three days로 바꿔놨고 적절한 이름 결정되면 파일 이름이랑 workflow 이름까지 한꺼번에 통일하도록 하겠습니다.

2022-05-11 08:37 UTC, next0262 commented on .github/workflows/72_hour.yml
> +      id: three_days
일단 Three days로 바꿔놨고 적절한 이름 결정되면 파일 이름이랑 workflow 이름까지 한꺼번에 통일하도록 하겠습니다.

2022-05-11 22:57 UTC, so931 approved these changes

2022-05-12 02:06 UTC, dshwpark approved these changes
코드 확인했습니다.

2022-05-12 02:09 UTC, merged