[AWIBOF-7406] Change POS service stop process
poseidonos/poseidonos pull request #551
Opened 2022-11-09 10:51 UTC by Seochokid

Modification of suspension method of Poseidon service taking into account the service lifecycle.
See IMS task for details.

2022-11-10 00:18 UTC, dshwpark commented on package/src/etc/poseidonos.service
> +KillSignal=SIGKILL
SIGKILL로 POS를 종료할 경우, 재시작 했을때 우리가 기대하는 state(array, volume 정보 및 data 유지)로 원복이 가능해지나요?

2022-11-10 00:47 UTC, so931 requested changes
jira에서 말씀하신 pos 정상종료 확인 동작이 누락된 것 같습니다.

또 이렇게 변경되면 stop=kill이라 현우님이 말씀하신 것 처럼 state가 모두 날라가게 되어 위험하네요. 
service, cli의 stop-start의 로직이 동일해야 하고 그렇다면 service에서 cli의 start/stop을 호출하는게 좋을 것 같은데 의견 부탁드립니다!

2022-11-10 01:03 UTC, Seochokid commented
> jira에서 말씀하신 pos 정상종료 확인 동작이 누락된 것 같습니다.
> 
> 또 이렇게 변경되면 stop=kill이라 현우님이 말씀하신 것 처럼 state가 모두 날라가게 되어 위험하네요. service, cli의 stop-start의 로직이 동일해야 하고 그렇다면 service에서 cli의 start/stop을 호출하는게 좋을 것 같은데 의견 부탁드립니다!

pos 정상종료 확인 동작을 넣고 systemctl stop을 통해 종료를 했을 때, 종료가 안되는 상황(array mount된 상황 등)일 때에는 spdk reset을 수행하지도 않고, pos process도 살아있지만, service는 fail 상태가 되어 더 이상 관리가 되지 않는 상황이 발생합니다. 이는 서비스가 systemctl stop 동작을 받으면 해당 process가 사라져야만 success로 인식하고 나머지는 fail로 인식해서 발생하는 것 같습니다. 따라서 systemctl stop을 통한 pos stop은 최후의 강제종료로 남겨두고, 보통의 pos 종료는 cli를 통해 해야하는 것으로 가이드 했습니다.

2022-11-10 02:40 UTC, so931 commented
> > jira에서 말씀하신 pos 정상종료 확인 동작이 누락된 것 같습니다.
> > 또 이렇게 변경되면 stop=kill이라 현우님이 말씀하신 것 처럼 state가 모두 날라가게 되어 위험하네요. service, cli의 stop-start의 로직이 동일해야 하고 그렇다면 service에서 cli의 start/stop을 호출하는게 좋을 것 같은데 의견 부탁드립니다!
> 
> pos 정상종료 확인 동작을 넣고 systemctl stop을 통해 종료를 했을 때, 종료가 안되는 상황(array mount된 상황 등)일 때에는 spdk reset을 수행하지도 않고, pos process도 살아있지만, service는 fail 상태가 되어 더 이상 관리가 되지 않는 상황이 발생합니다. 이는 서비스가 systemctl stop 동작을 받으면 해당 process가 사라져야만 success로 인식하고 나머지는 fail로 인식해서 발생하는 것 같습니다. 따라서 systemctl stop을 통한 pos stop은 최후의 강제종료로 남겨두고, 보통의 pos 종료는 cli를 통해 해야하는 것으로 가이드 했습니다.

확인했습니다. 설명 감사합니다ㅎㅎ

2022-11-10 02:41 UTC, so931 approved these changes

2022-11-11 07:34 UTC, dshwpark approved these changes

2022-11-11 08:13 UTC, merged