[AWIBOF-7964] disable vsc config added, disabled allocator::Beforeflu… (DRAFT)
poseidonos/poseidonos pull request #715
Opened 2023-02-10 01:34 UTC by ray5273

- vsc disabled on all configs
- disabled segmentctx flush, allocator ctx flush
- ci verification needed

CI 테스트 확인용 draft입니다.

2023-02-10 02:33 UTC, dhihm commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
이건 왜 삭제 된건가요?

2023-02-10 02:36 UTC, ray5273 commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
아 여기서 삭제된 부분이 allocatorCtx파일의 데이터를 버퍼에 옮겨주는 과정을 하는듯한데
 _CopySectionData에 이미 다 동일하게 존재해서 중복이라고 판단해서 지웠습니다.
심지어 여기서는 `StripeId currentSsdLsid;` 이 값을 버퍼에 복사해주지 않는것 같아서 문제가 있다고 판단해서 삭제해서 draft통해서 CI 돌려보는중입니다.

2023-02-10 03:47 UTC, ray5273 commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
조금 걸리는 부분은 lock을 잡고 있는 부분들인데요. memcpy전에 lock이 생긴 history를 정확히 몰라서요
혹시나 생길 이슈를 대비해서 이 부분에 currentSsdLsid memcpy하는 코드를 추가하고
allocator_ctx는 _CopySectionData()를 하지 않게 하면 위의 코드와 lock 잡는것 빼고는 완전히 동일 할 듯 합니다.

2023-02-10 06:56 UTC, dhihm commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
휴가나 교육전에는 코드를 고치지 않는다는 불문율을..

2023-02-11 05:31 UTC, ray5273 reviewed
이전 리뷰 커맨트 반영 ,CI fix, 필요없다고 생각되는 부분 fix를 진행하였습니다.
리뷰부탁드립니다.

2023-02-11 05:31 UTC, ray5273 commented on config/ibofos_for_psd_ci_wt.conf
> +        "enable_vsc": false
기존의 PSD CI 테스트는 이 부분에서 문제가 발생했습니다.

2023-02-11 05:31 UTC, ray5273 commented on test/unit-tests/allocator/context_manager/allocator_file_io_test.cpp
> +    // TODO(sang7.park) : To be fixed, maybe this test supposed to move tointeration test.
빠른 시간에 테스트를 작성하려고했으나,,
callback 관련된 것들을 실제로 불러내려다 보니 UT쪽에서 짜기에는 무리가 있는 코드라고 생각했습니다.
segmentInfo write자체는 잘 써지는것을 확인했으나 
대부분 real object를 쓰다보니 asyncio callback관련 SegmentationFault를 해결하기가 힘들어서 우선은 disabled 해두고 교육갔다와서 추가로 작성예정입니다 ㅠ_ㅠ

2023-02-11 05:31 UTC, ray5273 commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    currentPtr += GetSectionSize(AC_ACTIVE_STRIPE_TAIL);
이 부분의 코드를 보다가 조금 이상한 부분이 있었는데요.
allocatorCtx의 내용을 저장하기 위해서 버퍼를 준비하는 부분인데 기존의 structure 상 아래의 데이터가 buffer에 순차적으로 들어오는 것을 의도한것으로 보입니다.
```
enum AllocatorCtxSection
{
    AC_HEADER = 0,                       // AC 데이터 1
    AC_CURRENT_SSD_LSID,        // AC 데이터 2
    NUM_ALLOCATION_INFO,
    AC_ALLOCATE_WBLSID_BITMAP = NUM_ALLOCATION_INFO,  // AC 데이터 3
    AC_ACTIVE_STRIPE_TAIL,                                                                // AC 데이터 4
    NUM_ALLOCATOR_CTX_SECTION,
};
```
예상된 serialized data `AC데이터1 | AC데이터2 | AC데이터3 | AC데이터4`

하지만 위의 코드상 실제로는 header 데이터 직후에 바로 AC 데이터 3인 AC_ALLOCATE_WBLSID_BITMAP을 memcpy 합니다. 
실제 여기서 만든 버퍼는 오른쪽과 같이 됩니다.`AC데이터1 | AC데이터3 | AC데이터4`

그러면 기존에는 데이터 저장이 제대로 안됐는데 왜 문제가 생기지 않았냐고 의문이 생기실 수 있을텐데 
이 부분 직후에 AllocatorFileIo::_PrepareBuffer() 부분을 보시면 
client->BeforeFlush() 직후에 Rebuild_ctx가 아닌경우, _CopySectionData() 라는 함수를 호출합니다.
직전 beforeflush()에서 `AC데이터1 | AC데이터3 | AC데이터4` 로 저장된 데이터를 
_CopySectionData()에서 한번 더  `AC데이터1 | AC데이터2 | AC데이터3 | AC데이터4` 로덮어쓰기 해주기 때문에 결과자체는 문제가 없었었던것 같습니다.

결국 memcpy자체가 중복이기도 하고 조금 잘못되어있기도하여 이 부분을 삭제했습니다.
혹시나 잘못 된 부분이 있다면 알려주시면 감사드립니다!

2023-02-11 05:31 UTC, ray5273 commented on src/allocator/context_manager/segment_ctx/segment_info.h
> +struct SegmentInfoData
이전 리뷰 반영했습니다.

2023-02-13 02:09 UTC, dhihm commented on config/ibofos_for_psd_ci_wt.conf
> +        "enable_vsc": false
vsc enable 일때 왜 문제가 생기는지에 대한 분석 내용이 궁금하네요. 원래는 enable 때도 문제가 없었던 것 같은데.

2023-02-13 02:42 UTC, huijeong-kim requested changes

2023-02-13 02:42 UTC, huijeong-kim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
제가 이 코드 이해한 바로는 ㅎ
Copy 과정에서는 allocCtxLock만 잡기 떄문에, 그 lock이 아닌 별도의 lock을 사용하는 자료들은 해당 lock을 잡도록 여기서 추가 구현해준 느낌입니다 ㅎ allocatorFileIo에 의해 복사된 값은 atomicity가 지켜지지 않을 수 있는 데이터인데 여기서 덮어써 주니까 괜찮을 것 같다는 가정에요..? 근데 그래 보이는 것 치곤 또 복사 순서가 잘못되어있긴 합니다 ㅎ currentSsdLsid 는 allocatorFileIo에 의해 copy되고 다른 lock이 없기 떄문에 여기서 추가로 copy하지 않은 것 같고요. 아래에서 언급하신 offset 이 이상한 건 문제 있어 보입니다 ㅎㅎ 근데 역시 덮어써서 상관 없는 듯요..

2023-02-13 02:42 UTC, huijeong-kim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
제가 리팩토링하면서 이 부분도 수정하고 있었는데요.
PR 예정 코드와 겹쳐 또 리베이스 할 생각에 아득한데, 
불량 현상과 관련 없는 변경점이고 아직 테스트되지 않았다면 이번 PR에서 제외해주실 수 있나요?

2023-02-13 02:42 UTC, huijeong-kim commented on src/allocator/context_manager/segment_ctx/segment_info.cpp
> +    data = segmentInfoData;
테스트에서 Dependency Injection용으로도 사용하기 위해서 
초기화 된 data를 주입하는 건 어떤가요? 주어진 데이터를 다시 초기화 한다면 테스트 때 활용하지 못해 아쉬울 것 같은데요 ㅎ

2023-02-13 02:42 UTC, huijeong-kim commented on src/allocator/context_manager/segment_ctx/segment_info.cpp
> +    data = segmentInfoData;
그리고 생성자가 아닌 별도의 함수로 초기화하는 이유가 있을까요?

2023-02-13 02:42 UTC, huijeong-kim commented on config/ibofos_for_psd_ci_wt.conf
> +        "enable_vsc": false
이거 그럼 제가 enable 할 때 다시 분석하면 되는건가요?

2023-02-13 05:56 UTC, yyu-nim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
@huijeong-kim 님 설명 감사합니다! 아마 @ray5273 님께서 당분간 답변이 늦으실 것 같아 어쩌면 제가 대신 작업해드릴 수 있을 것 같기도 합니다 ㅎ 본 PR에서 `BeforeFlush()`에 가해진 변경점 부분만 다시 원복하고 다른 메서드의 변경점들은 그대로 두면 될까요?? (그래야 CI pre-/post- commit test를 통과할 수 있으므로??) 아니면 혹시 다른 아이디어 있으시면 알려주시길! 제안해주시는 내용으로 변경가하고 테스트 해보도록 하겠습니다 (@ray5273 님도 혹시 코멘트 확인하시면 아이디어 주시면 감사하겠습니다)

2023-02-13 05:58 UTC, yyu-nim commented on src/allocator/context_manager/allocator_file_io.cpp
> +    POS_TRACE_INFO(EID(ALLOCATOR_META_ASYNCLOAD), "[AllocatorLoad] try to load section data");
`[AllocatorLoad]` 부분은 삭제해도 될 것 같습니다. 이것이 주는 추가적인 정보가 있다면, event id 자체 혹은 log message 자체를 보강하는게 좋을 것 같습니다

2023-02-13 06:02 UTC, yyu-nim commented on src/allocator/context_manager/segment_ctx/segment_info.cpp
> +    data = segmentInfoData;
@ray5273 님 코멘트 주시면 좋을 것 같고, 없으시면 @huijeong-kim 님 코멘트 반영해보도록 하겠습니다 ㅎ 그 경우 대략 아래 모양이 되겠네요
```c++
auto& segmentInfoData = SegmentInfoData::new();
auto& segmentInfo = SegmentInfo::new(std::move(segmentInfoData));
```

2023-02-13 06:05 UTC, yyu-nim commented on src/journal_manager/log_buffer/versioned_segment_ctx.cpp
> +        segmentInfos[segId].AllocateAndInitSegmentInfoData(&segmentInfoDatas[segId]);
```c++
segmentInfos = new SegmentInfo[numSegments];
...
for (auto segId=0; segId< numSegments; segId++) {
  ...
  segmentInfos[segId] = SegmentInfo::new(&segmentInfoDatas[segId]);
  ...
}
```
위에 @huijeong-kim 님 코멘트 반영하면 이런 모양이 되겠네요 @ray5273 어떠신가요???

2023-02-13 06:06 UTC, yyu-nim commented on test/unit-tests/allocator/context_manager/allocator_file_io_test.cpp
> +    // TODO(sang7.park) : To be fixed, maybe this test supposed to move tointeration test.
저도 한번 살펴보겠습니다 가능하면 통합 테스트 몇개 들어갈 수 있으면 좋을 것 같아서요

2023-02-13 06:08 UTC, yyu-nim commented
이 PR 제가 이어 받아 작업해보도록 하겠습니다. 코멘트 추가로 있으시면 언제든 남겨주시길. 감사합니다.

2023-02-13 06:41 UTC, huijeong-kim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
현재 제가 이해하는 바로는 코드 변경점 중에 CI test 와 연관 있는 것은 없는 걸로 알고 있는데, 다른 method 수정점이 CI 이슈와 관련이 있을까요...?

아무튼 지난 코드 리뷰 의견 반영건 제외 변경점(바로 이 함수)는 넣지 않아도 좋을 것 같습니다 ㅎㅎ

2023-02-13 06:59 UTC, yyu-nim commented on config/ibofos_for_psd_ci_wt.conf
> +        "enable_vsc": false
일단 제가 enable 하고 한번 다시 돌려보도록 하겠습니다 
`test/system/spor# ./run_all_tests.py ` 
`test/system/io_path/precommit_loopback_test.sh`
돌려볼 생각이고, config는 `ibofos_for_psd_ci_wt` 에서 enable_vsc: true만 override 해서 결과 공유 드릴께요

2023-02-13 08:57 UTC, yyu-nim commented
PR #717 이 먼저 merge 되고 나서 본 #715 가 들어가도 되겠다 싶은 느낌입니다. 일단 PR #717 리뷰 완료될 때까지는, 본 PR의 merge 는 잠시 미루도록 하겠습니다. fyi @huijeong-kim @ray5273

2023-02-13 13:26 UTC, ray5273 commented on src/allocator/context_manager/segment_ctx/segment_info.cpp
> +    data = segmentInfoData;
어.. 약간 취향..? 이랄까요.. 
생성자에서 해줘도 되긴한데 initialize를 명시적으로 해주는게 좀 확실할것 같다는 생각이 들어서요
없는것도 사실 괜찮습니다!

2023-02-13 13:27 UTC, ray5273 commented on src/allocator/context_manager/allocator_file_io.cpp
> +    POS_TRACE_INFO(EID(ALLOCATOR_META_ASYNCLOAD), "[AllocatorLoad] try to load section data");
아 이 부분은 디버깅용이였는데 들어가버렸네요..;

2023-02-14 08:17 UTC, yyu-nim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> -    char* currentPtr = buf;
1) AllocatorCtx::BeforeFlush() 원상 복구, 2) UT 깨진 것 하나 수정 하여 push 하였습니다.

2023-02-14 08:19 UTC, yyu-nim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> +
```c++
void
AllocatorCtx::BeforeFlush(char* buf)```
이 부분이 원복 되어  highlight 되지 않으니 참고 부탁드립니다 (fyi @huijeong-kim @ray5273 )

2023-02-14 08:20 UTC, yyu-nim commented on src/allocator/context_manager/allocator_ctx/allocator_ctx.cpp
> +
이 빈칸도 없애겠습니다;

2023-02-14 08:27 UTC, yyu-nim commented
rebase 한 뒤에 테스트 결과 다시 봐야 할 것 같습니다.

2023-02-14 08:47 UTC, yyu-nim commented
> rebase 한 뒤에 테스트 결과 다시 봐야 할 것 같습니다.

Rebased 후 forced-push 하였습니다 로컬에서 ut 돌려보았는데 ci precommit test도 확인해봐야 할 것 같습니다.

2023-02-15 10:14 UTC, yyu-nim approved these changes

2023-02-15 23:52 UTC, yyu-nim commented
enable_vsc 의 여부와 관계없이 local test 에서 hang 현상 보이는 부분있어 추가 분석 중입니다. 분석 완료 되기 전까지는 merge 를 미루도록 하겠습니다

2023-02-15 23:53 UTC, yyu-nim requested changes
test failure 정상화 후 merge

2023-02-16 02:36 UTC, yyu-nim commented
https://github.com/poseidonos/poseidonos/pull/719
merge 된 후, 본 PR 테스트후 merge 할것

2023-02-16 08:09 UTC, huijeong-kim commented on src/allocator/context_manager/segment_ctx/segment_info.cpp
> +    data = segmentInfoData;
초기화 방식이 생성자, Initialize로 나눠진 경우에는 테스트가 좀 복잡해지는 것 같더라고요ㅎㅎ Init을 빼먹어도 어떤 건 테스트 가능하고 어떤 건 안되곤 하는데, 그런지 아닌지를 일일이 구현을 다 살펴봐야 해서요. 그래서 말씀드렸습니다. ㅎㅎ

2023-02-20 03:08 UTC, yyu-nim commented
Rebase 및 로컬 UT/IT 성공 확인하였습니다.

2023-02-20 03:52 UTC, yyu-nim submitted a review, later dismissed

2023-02-20 03:52 UTC, yyu-nim commented on config/ibofos_for_psd_ci_wt.conf
> +        "enable_vsc": false
local에서 spor 테스트시 enable_vsc false/true 여부 관계없이 통과하는 것으로 확인되었습니다 (PR#719 머지 이후 기준). `enable_vsc: false` 변경점은 bug fix 라기 보다는, "기대하는 테스트 config로 정정한다" 정도로 봐주시면 될 것 같습니다

2023-02-20 03:52 UTC, yyu-nim commented on src/allocator/context_manager/segment_ctx/segment_ctx.cpp
> +            segmentInfos[i].AllocateAndInitSegmentInfoData(&segmentInfoData.data[i]);
예전에 여기 PR인가 이전PR에서, AllocateSegment()과 InitSegment()를 분리하는 이유에 대한 코멘트가 있었던 것 같은데, 이번 rebase 하면서 보니, 현재 UT 작성을 위해 일부는 외부에서 segment state를 미리 대입해서 주입하도록 되어 있어서, 이 때는 `AllocateSegmentInfoData()` 를 사용해서 pre-conditioned segment state를 건드리지 않고 그대로 두도록 하고, Prod code에서 bring up 시에 초기화하는 부분에서는 `AllocateAndInitSegmentInfoData()`를 사용하면 될 것 같습니다.

2023-02-20 03:52 UTC, yyu-nim commented on src/allocator/context_manager/segment_ctx/segment_info.cpp
> +SegmentInfo::AllocateSegmentInfoData(SegmentInfoData* segmentInfoData)
`segment_ctx.cpp`에서 적었던 이유로, UT context에서는 `AllocateSegmentInfoData()`를 사용해서 미리 조건을 맞춰둔 segment info data를 주입만 하도록 하는 (즉, 초기화 없이) API가 필요해서 다시 살렸습니다

2023-02-20 03:52 UTC, yyu-nim commented on src/allocator/context_manager/segment_ctx/segment_info.h
> +        SegmentInfoData(0, 0, SegmentState::FREE);
초기화가 없어 coverity issue 로 보고되어 (AWIBOF-8089), 여기에 미리 넣어둡니다

2023-02-20 03:52 UTC, yyu-nim commented on test/unit-tests/allocator/context_manager/allocator_file_io_test.cpp
> +    // TODO(sang7.park) : To be fixed, maybe this test supposed to move tointeration test.
DISABLED 된것 해제하고 다시 테스트 해보도록 하겠습니다

2023-02-20 03:52 UTC, yyu-nim commented on test/unit-tests/allocator/context_manager/segment_ctx/segment_ctx_test.cpp
> +    SegmentInfoData* segmentInfoData = new SegmentInfoData[numSegments];
`new SegmentInfoData[numSegments](0, 0, SegmentState::FREE)` 이런 패턴에서 compiler warning이 계속 생겨서 (뭔가 되는 것 같긴 한데, 빌드 로그가 노이즈가 많아져서), 다음 라인에서 명시적으로 for loop 돌면서 초기화하는 형태로 변경하였습니다.

2023-02-20 07:34 UTC, yyu-nim commented on test/integration-tests/allocator/allocator_file_io_integration_test.cpp
> +TEST(AllocatorFileIo, InitBeforeFlushAfterLoad_testIfSegmentCtxIsSerializedAndDeserializedProperly)
Disable 되어 있었던 integration 살려서, bug fix후 위치 옮겨 여기 두었습니다.

2023-02-20 07:35 UTC, yyu-nim approved these changes

2023-02-21 00:34 UTC, yyu-nim commented on src/allocator/context_manager/segment_ctx/segment_info.h
> +    void Set(uint32_t validBlockCount, uint32_t occupiedStripeCount, SegmentState segmentState)
Setter 하나 추가해두었습니다

2023-02-21 00:34 UTC, yyu-nim commented on test/integration-tests/allocator/allocator_file_io_integration_test.cpp
> +    }
c++ 에서 file size 읽어오는 쉬운 방법을 찾다가 위 방법을 찾은건데, 혹시 더 나은 방법이나 라이브러리 있으시면 추천해주시면 살펴보겠습니다

2023-02-21 00:35 UTC, yyu-nim commented on test/integration-tests/allocator/allocator_file_io_integration_test.cpp
> +    //         Also, the segment context should
주석을 쓰다 말고 다른 일 하다 잊었던것 같네요; 완성하도록 하겠습니다

2023-02-21 00:37 UTC, yyu-nim commented on test/integration-tests/journal/fake/i_segment_ctx_fake.cpp
> +            segmentInfos[i].SetState(SegmentState::FREE);
위에 추가된 Setter를 쓸 수도 있는데, 그 경우 segment info의 member를 직접 접근해야 해서, 일단은 기존 코드로 두겠습니다. 만약 Setter를 쓰게 되면
```c++
segmentInfos[i].data->Set(0, 0, SegmentState::FREE);
```
가 될 것입니다만..

2023-02-21 00:38 UTC, yyu-nim commented on test/integration-tests/journal/replay_log_buffer_integration_test.cpp
> +TEST_F(ReplayLogBufferIntegrationTest, DISABLED_ReplayFullSegmentWhenCheckpointFailEventIfSegmentContextFlushed)
AWIBOF-8054 생성해두었습니다.

2023-02-21 00:43 UTC, dhihm approved these changes

2023-02-21 06:11 UTC, merged