[AWIBOF-8105] Add replay task to load Versieond Segment Context from updated segment context
poseidonos/poseidonos pull request #742
Opened 2023-03-06 02:00 UTC by cheolho-kang

[Revieweee]
- Review 목적: VSC Load 시점을 Replay 가 모두 끝난 뒤로 옮기기
- 참고 문서: IMS
- 주요 review 파일: versioned_segment_ctx.cpp, load_versioned_segment_context.cpp
- 검증 방법 또는 TC: UT/IT

[Reviewer]
- Checklist

2023-03-06 02:39 UTC, cheolho-kang commented on src/journal_manager/journal_manager.cpp
> -
이부분은 replay에서 load하도록 task를 따로 뺐습니다

2023-03-06 02:39 UTC, cheolho-kang commented on src/journal_manager/log_buffer/versioned_segment_ctx.cpp
> +VersionedSegmentCtx::Init(JournalConfiguration* journalConfiguration, uint32_t numSegments_)
Replay때 load 되는 경우 외에는 모두 Init 상태로 SegmentInfo를 새로 생성해서 사용하기 때문에 loadedSegmentInfo 인자를 제거하였습니다

2023-03-06 02:39 UTC, cheolho-kang commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +/*
이름 짓기가 쉽지 않네요.. 이름 추천 부탁드립니다 ㅠ

2023-03-06 02:39 UTC, cheolho-kang commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
마지막 task에서 Versioned Segment Context를 load하도록 task를 추가하였습니다

2023-03-06 02:39 UTC, cheolho-kang commented on test/integration-tests/allocator/context_manager_integration_test.cpp
> -    SegmentInfo* loadedSegInfos;
Versioned Segment Context를 사용할 때
Segment Context를 load해서 사용하는 시나리오가 딱히 있진 않았어서 제거하였습니다.

2023-03-06 02:39 UTC, cheolho-kang commented on test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp
> +class VersionedSegmentCtxTestFixture : public testing::Test
Segment Info를 세팅하는 과정이 모든 TEST마다 동일하게 있어서
중복 코드를 제거하기 위해 TestFixture로 수정하였습니다

2023-03-06 02:39 UTC, cheolho-kang commented on test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp
> +    versionedSegCtx.Load(segmentInfos);
SegmentInfo 변경후 Load해서 검증하는 시나리오에 대해서만 다음과 같이 Load 함수를 호출하여 테스트하도록 수정하였습니다

2023-03-06 03:30 UTC, yyu-nim reviewed
수고 많으셨습니다!!! 코멘트만 확인후 approve 하도록 하겠습니다

2023-03-06 03:30 UTC, yyu-nim commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +/*
저는 괜찮은 것 같습니다 ㅎ 혹시 나중에라도 생각나면 이름 업데이트 하겠습니다

2023-03-06 03:30 UTC, yyu-nim commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +    }
여기랑 line 73의 Else에 warning/error log 넣는 것은 어떨까요??? 혹시 UT context 에서 nullptr이 될 수 있음을 허용한다고 하면, 그 내용을 comment로 적어주셔도 좋을 것 같아요 예를 들면
```c++
if ( nullptr != contextManager ) {
  ...
} else {
  // reachable only in UT context
}
```
contextManager 가 nullptr일 경우, line 76에 nullptr가 넘어가게 될 텐데 이 경우 문제없게 될지도 한번 확인해주시면 좋을 것 같습니다

2023-03-06 03:30 UTC, yyu-nim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
추후에 새로운 `ReplayTask`가 추가되거나 뭔가 리팩토링이 필요해서 이 부근에 순서 변경이 생길 경우, "반드시 만족되어야 할 순서"는 어떻게 될까요??? 가령 `LoadVersionedSegmentContext`는 `ReplayLogs` 이후에 와야 한다 라던지 (지어냈습니다 ㅎ), 그런 제약이 있다면 comment로 남겨주셔도 좋을 것 같습니다

2023-03-06 03:30 UTC, yyu-nim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
아니면, 반드시 "항상 마지막" 이어야만 한다 라고 하면, 그 내용을 코멘트로 달아서 추후에 다른 누군가가 새로 replay task를 추가하더라도 이 순서를 어기지 않도록 경고를 줄 수 있으면 좋을 것 같습니다

2023-03-06 03:30 UTC, yyu-nim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
한가지 더는, versioned segment context 의 pos.conf에 있는 feature flag 랑 관계없이 항상 이 replay task를 실행하는 디자인으로 보면 될지요. vsc disabled 인 POS에서 LoadVersionedSegmentContext는 no-op이 될지 아니면 뭔가 side effect를 일으킬지 궁금합니다

2023-03-06 04:55 UTC, ray5273 approved these changes
LGTM! 고생하셨습니다 ㅎㅎ

2023-03-06 04:55 UTC, ray5273 commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +    return 10;
weight는 혹시 어떤용도인지 알 수 있을까요?

2023-03-06 05:07 UTC, cheolho-kang commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +    return 10;
ReplayProgressReporter가 Replay 진행 상황을 표시할 때 사용하는 각 task별 weight 입니다.
참고로 각 task별 weight은 다음과 같습니다.
1. ReadLogBuffer: 40
2. FilterLogs: 10
3. ReplayLogs: 30
4. ReplayVolumeDeletion: 10
5. FlushMetadata: 20
6. ResetLogBuffer: 10
7. FlushPendingStripes: 10
**8. LoadVersionedSegmentContext: 10**

이 코드를 보시면 이해하시기 편하실거같아 첨부드립니다.

```
void
ReplayProgressReporter::_ReportProgress(void) {
    int percent = (progress + currentTaskProgress) * 100 / totalWeight;
    if (percent != reportedProgress)
    {
        POS_REPORT_TRACE(EID(SYSTEM_RECOVERY),
            "progress report: [" + to_string(percent) + "]");
        usleep(100 * 1000); // delay for the m-tool integration
        reportedProgress = percent;
    }
}
```

2023-03-06 05:19 UTC, huijeong-kim requested changes
고생많으셨습니다!
ReplayTask 순서만 확인 부탁드립니다.

2023-03-06 05:19 UTC, huijeong-kim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
Load Task를 FlushPendingStripes 보다 앞에 위치시키는 게 더 좋을 것 같아요. FlushPendingStripes 단계에서 stripe flush로 인해 추가 map/allocator meta 업데이트가 발생할 수 있기 때문에요. 

물론.. 지금은 로드가 조금 늦게 되어도 크게 문제는 없을 것 같다는 생각이 들지만, FlushPendingStripes 과정에서 checkpoint 가 발생한다면 (현재는 낮은 가능성, 하지만 checkpoint 기준을 바꾼다면 쉽게 발생할 수 있음) load 되기 전에 checkpoint가 발생해 문제될 수 있을 것 같습니다 ㅎㅎ

2023-03-06 05:19 UTC, huijeong-kim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
순서에 대한 건 replay_handler_test.cpp에 UT 추가할 수 있을 것 같아요!
journal_manager_test.cpp Init_testWithJournalEnabledAndLogBufferNotExist 에서 LogFilledSubscriber 등록 순서 테스트한 것 처럼요

2023-03-06 05:19 UTC, huijeong-kim commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +/*
좋은 것 같습니다! ㅎㅎ

소소한 의견은 "Versioned"는 빼도 좋을 것 같기도 합니다. 엄밀히 말하면 SC version을 로드하는 게 아니라서..  `LoadSegmentContext`  아님 `LoadReplayedSegmentContext`..? 같은 것도 좋을 것 같습니다.

2023-03-06 05:19 UTC, huijeong-kim commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +    return 10;
이거... 현재 100이 넘어도 문제 없게 구현되어있긴 한데 원래는 10 늘린 만큼 다른 task에서 빼줘야 더 좋을 것 같긴 합니다 ㅋㅋ 다음에 task weight table을 어디다 만들어 둬야 겠어요...

2023-03-06 05:19 UTC, huijeong-kim commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +  contextManager(contextManager),
몬가 UT와 엮여있던 것 같기도 하지만,,
`ContextManager`가 아닌 `SegmentCtx`를 전달해 주면 좋을 것 같습니다 ㅎㅎ

2023-03-06 05:19 UTC, huijeong-kim commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +    return 10;
Replay Progress 를 100분위로 표현할 때 사용하는 값으로, 전체 Task 중 이 ReplayTask의 비중을 의미합니다 ㅎ

2023-03-06 05:19 UTC, huijeong-kim commented on test/integration-tests/allocator/context_manager_integration_test.cpp
> -    SegmentInfo* loadedSegInfos;
나중에 쓸려고 둔 것 같기도 하고요..?!
나중에 테스트 작성할 때 ON_CALL로 버퍼 Load시 전달하는 버퍼 등록해 두는 것도 좋을 것 같습니다 ㅎㅎ

2023-03-06 05:48 UTC, cheolho-kang reviewed
리뷰 감사합니다. 내용 반영하였습니다

2023-03-06 05:48 UTC, cheolho-kang commented on src/journal_manager/replay/load_versioned_segment_context.cpp
> +    }
아! 넵, VersionedSegmentCtx::Load()에서 nullptr가 아닐 때에만 load를 하기 때문에 문제없이 진행됩니다. 좀더 정확하게 표기하기 위해 VersionedSegmentCtx::Load에서 nullptr에 해당하는 로깅 추가하였습니다

2023-03-06 05:48 UTC, cheolho-kang commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
**Feature flag 관련**
- VSC가 disable일 경우 dummy VSC가 로드되어있기 때문에 versioned_segment_ctx.h에 추가한

```
virtual void Load(SegmentInfo* loadedSegmentInfo) override {}
```
가 호출되어 side effect은 없을것이라 생각됩니다.

**Replay Task 순서 관련**
- 아! 넵넵 코멘트를 추가해두겠습니다. 그리고 만약 지금과 같은  Replay 완료후 Load동작들이 더 추가로 생기게 된다면 Load Task로 묶어서 맨 마지막에 호출되도록 하는 것도 방법일 것 같다는 생각이 드네요..!

2023-03-06 05:50 UTC, cheolho-kang commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
아 그러네요. FlushPendingStripes에서 발생하는 Segment Context Update까지 모두 완료된 후에 Load해야겠다라고만 생각했는데,
다시 자세히 고민해보니. 이때는 Versioned Segment Context를 직접 업데이트 시킬 것이기 때문에, 위로 올리는게 나을것같네요.
 수정하겠습니다!

2023-03-06 07:13 UTC, cheolho-kang reviewed
리뷰 감사합니다

2023-03-06 07:13 UTC, cheolho-kang commented on test/integration-tests/allocator/context_manager_integration_test.cpp
> -    SegmentInfo* loadedSegInfos;
아하 넵넵! 테스트 추가하게 될때 ON_CALL 활용해서 사용해보겠습니다!

2023-03-06 08:25 UTC, yyu-nim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadVersionedSegmentContext(contextManager, versionedSegCtx, reporter));
그러네요 UT로 강제될 수 있으면 더 좋을 것 같네요!

2023-03-07 01:40 UTC, yyu-nim submitted a review, later dismissed

2023-03-07 07:47 UTC, huijeong-kim approved these changes
수정과 테스트 추가 감사합니다! 고생 많으셨습니다 :)

2023-03-07 08:38 UTC, huijeong-kim submitted a review, later dismissed

2023-03-08 03:02 UTC, yyu-nim commented on src/journal_manager/replay/replay_handler.cpp
> +    _AddTask(new LoadReplayedSegmentContext((SegmentCtx*)segmentCtx, versionedSegCtx, reporter));
주석 추가 감사합니다!

2023-03-08 03:03 UTC, yyu-nim commented on test/integration-tests/journal/fake/allocator_mock.cpp
> +AllocatorMock::AllocatorMock(TestInfo* testInfo, IArrayInfo* info)
엇.. 비슷한 PR을 다른데서도 본 것 같은데, 혹시 두 PR이 모두 Merge되는 걸지 아니면 이 PR은 discard 되는 것일지요??

2023-03-08 03:06 UTC, yyu-nim commented on test/integration-tests/journal/fake/allocator_mock.cpp
> +AllocatorMock::AllocatorMock(TestInfo* testInfo, IArrayInfo* info)
https://github.com/poseidonos/poseidonos/pull/726

2023-03-08 03:26 UTC, yyu-nim commented on test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp
> +        int numSegInfos = 3;
`numSegInfos`도 `numLogGroups` 처럼 class level member variable로 빼내는게 좋을까요?? 로컬 변수로 일부러 의도적으로 두신 것인지 궁금합니다

2023-03-08 03:28 UTC, yyu-nim commented on test/unit-tests/journal_manager/replay/replay_handler_test.cpp
> +        // Then: All replay tasks will be registered in this sequence
테스트 간결하고 좋네요!

2023-03-08 03:29 UTC, yyu-nim approved these changes
수고 많으셨습니다!!!

2023-03-08 05:06 UTC, huijeong-kim commented on test/integration-tests/journal/fake/allocator_mock.cpp
> +AllocatorMock::AllocatorMock(TestInfo* testInfo, IArrayInfo* info)
그러게요 변경점이 같네요.. ;_; 커밋정리해야할것같아요

2023-03-08 05:49 UTC, dhihm approved these changes

2023-03-08 10:08 UTC, cheolho-kang commented on test/unit-tests/journal_manager/log_buffer/versioned_segment_ctx_test.cpp
> +        int numSegInfos = 3;
아..! log group은 Setup이후에도 계속 사용되지만, numSegInfos는 그렇지 않아서 따로 만들진 않았습니다.
혹시 필요해지면 그때 수정해보겠습니다! 리뷰 감사합니다

2023-03-08 10:08 UTC, cheolho-kang commented on test/integration-tests/journal/fake/allocator_mock.cpp
> +AllocatorMock::AllocatorMock(TestInfo* testInfo, IArrayInfo* info)
아 그러게요 ㅎㅎ;; 수정하였습니다!

2023-03-08 12:21 UTC, yyu-nim approved these changes

2023-03-08 22:47 UTC, yyu-nim approved these changes

2023-03-09 01:18 UTC, huijeong-kim approved these changes

2023-03-09 01:18 UTC, merged